# Generated by Django 3.0.6 on 2020-06-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200611_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='likescount',
            name='dislikes_number',
            field=models.IntegerField(default=0, verbose_name='嫌弃数'),
        ),
        migrations.DeleteModel(
            name='DislikesCount',
        ),
    ]
