# Generated by Django 3.0.6 on 2020-06-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20200611_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesrecord',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
