# Generated by Django 3.0.6 on 2020-05-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtype',
            name='type_name',
            field=models.CharField(max_length=30, verbose_name='分类标签'),
        ),
    ]
