# Generated by Django 3.0.6 on 2020-06-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200601_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['pk']},
        ),
    ]
