# Generated by Django 3.0.6 on 2020-06-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200603_1645'),
        ('blog', '0007_auto_20200603_2045'),
    ]

    operations = [
    ]
