# Generated by Django 3.0.6 on 2020-06-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200603_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='upper_business',
            field=models.IntegerField(blank=True, null=True, verbose_name='上级业务层级'),
        ),
    ]
